# name of workflow that will be displayed on the actions page
name: BWA MEM test

# event that will cause the workflow to be executed
on:
  push:
    paths:
      - '.github/workflows/bwa.yml'

# a list of the jobs that run as part of the workflow
jobs:
  bwa_mem:
    # the type of runner to run the given job
    runs-on: ubuntu-latest

    # a list of the steps that will run as part of the job
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      # uses an action named actions/checkout@v2, which will check out the repository onto the runner
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."

      - name: Prepare environment
        run: |
          mkdir -p {tools/bin,src,result}
          echo "$GITHUB_WORKSPACE/tools/bin" >> $GITHUB_PATH
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Download files
        run: |
          mkdir -p raw
          wget -O raw/ERR031940_1.filt.fastq.gz https://davetang.org/file/single_exome/ERR031940_1.filt.fastq.gz
          wget -O raw/ERR031940_2.filt.fastq.gz https://davetang.org/file/single_exome/ERR031940_2.filt.fastq.gz
          wget -O raw/Homo_sapiens_assembly38.fasta https://storage.googleapis.com/genomics-public-data/resources/broad/hg38/v0/Homo_sapiens_assembly38.fasta

      - name: Compile tools
        run: |
          cd src
          wget --quiet https://github.com/lh3/bwa/archive/refs/tags/v0.7.17.tar.gz
          tar -xzf v0.7.17.tar.gz
          cd bwa-0.7.17 && make && mv bwa $GITHUB_WORKSPACE/tools/bin
          #          cd ..
          #          ver=1.14
          #          dir=$GITHUB_WORKSPACE/tools
          #          for tool in htslib bcftools samtools; do
          #             url=https://github.com/samtools/${tool}/releases/download/${ver}/${tool}-${ver}.tar.bz2
          #             wget --quiet ${url}
          #             tar xjf ${tool}-${ver}.tar.bz2
          #             cd ${tool}-${ver}
          #             ./configure --prefix=${dir}
          #             make && make install
          #             cd ..
          #          done

      - name: BWA index
        run: cd raw && bwa index Homo_sapiens_assembly38.fasta

      - name: BWA MEM
        run: |
          bwa mem -t 2 raw/Homo_sapiens_assembly38.fasta raw/ERR031940_1.filt.fastq.gz raw/ERR031940_2.filt.fastq.gz > result/ERR031940.sam

      - name: Job status
        run: echo "This job's status is ${{ job.status }}."

